# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

firstNumber = 1
secondNumber = 2
thirthNumber = 0

fibonacciSequence = [firstNumber, secondNumber]

for i in range(int(1e1) - 2):
    thirthNumber = firstNumber + secondNumber
    fibonacciSequence.append(thirthNumber)
    firstNumber = secondNumber
    secondNumber = thirthNumber
    

# print(*fibonacciSequence)

sumOfEvenItems = 0
for item in fibonacciSequence:
    if item % 2 == 0:
        sumOfEvenItems+=item

print('The sum of the even-valued terms in our fibonacci sequence is {}'.format(sumOfEvenItems))